### ISSUE TITLE
Ubuntu 20.04 the game does not start, libGL errors.

### ISSUE THREAD

**Issue by Yoshimitzy** [AM2R-Community-Developers/AM2RLauncher#10]
Hi! The game does not start, this is what it says in the terminal:
YoYo Games Linux Runner V1.3
CommandLine: -game game.unx
ExeName= /tmp/.mount_AM2R.AO7u4qJ/usr/bin/AM2R�
MemoryManager allocated: 17920
YoYo Games Runner v1.0(999)[r32908]
RunnerLoadGame: game.unx
RunnerLoadGame() - assets/game.unx
Checking if INIFile assets/options.ini Exists
!!!!No INI File assets/options.ini
Reading File assets/game.unx
Loaded File assets/game.unx(68872432)
IFF wad found
Get Resolution
Get Header Information
InitGMLFunctions
HighScore..SavePrePend /home/diablero/.config/AM2R/ 
Game..Math..Graphic..Action..File..Resource..Interaction..3D..Particle..Misc..DS..Sound..Physics..Gamepad..GAMEPAD: Initialising Ubuntu support
GAMEPAD: 4 axis values (last) at 0xf68a3660
GAMEPAD: 4 axis values (last) at 0xf68a3640
GAMEPAD: 4 axis values (last) at 0xf68a3620
GAMEPAD: 4 axis values (last) at 0xf68a3600
Buffers..Networking..Shaders..InitPushFunctions...YoYo..Fini
ID_STRG
Create Window
Display Size(Pixels): 3840,2160
GameDisplayName=AM2R
Win #1
XF86VidModeExtension-Version 2.2
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Only Singlebuffered Visual!
glX-Version 1.4

Nvidia drivers - 465.27. Output in terminal:
find /usr -iname "*libGL.so*" -exec ls -l -- {} + 
lrwxrwxrwx 1 root root     14 ноя 24 13:55 /usr/lib/i386-linux-gnu/libGL.so.1 -> libGL.so.1.7.0
-rw-r--r-- 1 root root 439868 ноя 24 13:55 /usr/lib/i386-linux-gnu/libGL.so.1.7.0
lrwxrwxrwx 1 root root     36 апр 29 16:35 /usr/lib/libGL.so.1 -> /usr/lib/x86_64-linux-gnu/libGL.so.1
lrwxrwxrwx 1 root root     14 ноя 24 13:55 /usr/lib/x86_64-linux-gnu/libGL.so.1 -> libGL.so.1.7.0
-rw-r--r-- 1 root root 547152 ноя 24 13:55 /usr/lib/x86_64-linux-gnu/libGL.so.1.7.0

The program asks for the swrast driver, but it has been removed from the debian distributions and from the mesa too. How to get to use opengl, vulkan?

**Comment by Miepee** [comment]
Hello, can you please post more system inforamation?
Specifically, Distro, CPU, GPU, and RAM information.

**Comment by Yoshimitzy** [comment]
inxi -F
System:    Host: diablero-System-Product-Name Kernel: 5.8.0-53-generic x86_64 bits: 64 Desktop: Gnome 3.36.7 
           Distro: Ubuntu 20.04.2 LTS (Focal Fossa) 
Machine:   Type: Desktop Mobo: ASUSTeK model: Z170-P v: Rev X.0x serial: <superuser/root required> 
           UEFI [Legacy]: American Megatrends v: 1804 date: 06/07/2016 
CPU:       Topology: Quad Core model: Intel Core i7-6700K bits: 64 type: MT MCP L2 cache: 8192 KiB 
           Speed: 2339 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 944 2: 1314 3: 1209 4: 1272 5: 1026 6: 1112 7: 1266 
           8: 944 
Graphics:  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] driver: nvidia v: 465.27 
           Display: x11 server: X.Org 1.20.9 driver: nvidia resolution: 3840x2160~60Hz 
           OpenGL: renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 465.27 
Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio driver: snd_hda_intel 
           Device-2: NVIDIA GP102 HDMI Audio driver: snd_hda_intel 
           Device-3: Aureal Vortex 2 driver: snd_au8830 
           Sound Server: ALSA v: k5.8.0-53-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp6s0 state: up speed: 100 Mbps duplex: full mac: d0:17:c2:ce:e6:66 
           IF-ID-1: enxcab5b791e7ad state: down mac: ca:b5:b7:91:e7:ad 
Drives:    Local Storage: total: 2.65 TiB used: 1.94 TiB (73.4%) 
           ID-1: /dev/nvme0n1 vendor: Western Digital model: WDS250G3X0C-00SJG0 size: 232.89 GiB 
           ID-2: /dev/sda vendor: Western Digital model: WD5000AZLX-00CL5A0 size: 465.76 GiB 
           ID-3: /dev/sdb vendor: Western Digital model: WD20PURX-64P6ZY0 size: 1.82 TiB 
           ID-4: /dev/sdc vendor: Hitachi model: HTS542516K9SA00 size: 149.05 GiB 
Partition: ID-1: / size: 227.74 GiB used: 72.33 GiB (31.8%) fs: ext4 dev: /dev/nvme0n1p5 
Sensors:   System Temperatures: cpu: 38.0 C mobo: N/A gpu: nvidia temp: 55 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 27% 
Info:      Processes: 354 Uptime: 6h 02m Memory: 31.31 GiB used: 4.46 GiB (14.2%) Shell: bash inxi: 3.0.38

**Comment by Miepee** [comment]
Go to the Launcher settings, and set put this `LD_PRELOAD=/usr/lib/i386-linux-gnu/libGL.so.1` into the enviroment variable text box and try again.

**Comment by Yoshimitzy** [comment]
It works! Thank you so much! Although I tried to launch the launcher itself with this command: LD_PRELOAD=/usr/lib/i386-linux-gnu/libGL.so.1 ./AM2RLauncher.Gtk but it did not help, maybe I did something wrong or wrote. Thanks a lot again!

**Comment by Miepee** [comment]
No problem.
Yeah you're supposed to put that into the text box, not launch the Launcher that way. This text box will remember that command now, so you shouldn't have any further issues.
