### ISSUE TITLE
Auto-climb doesn't work even though it is enabled

### ISSUE THREAD

**Issue by Detrixukaon58** [AM2R-Community-Developers/AM2RLauncher#13]
So I've fairly new to this game specifically, so please mind me if there was an update post about this as I could not find anything regarding this on google.

I had started playing AM2R before using the launcher and I was able to use the auto-climb feature perfectly fine, but when I started using the AM2R Launcher all of a sudden the auto-climb feature stopped working. Here's a video of what I see and my button inputs. 
![out5](https://user-images.githubusercontent.com/20668560/120225455-313ff200-c23d-11eb-8010-5be1830f20d4.gif)

This issue only arrised after I started using the launcher, so that is why I am asking here about it.

Here is information on the system I am running this on if this is needed.

OS: Windows 10 20H2
GPU: Nvidia GTX 1060 6GB
CPU: Intel i7-7700HQ
RAM: 16GB

**Comment by Miepee** [comment]
Issue closed, not AM2RLauncher related.
Please repost it to this repository instead, thanks
https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/issues

**Comment by Detrixukaon58** [comment]
Thanks for clarifying. Sorry for any inconvenience I've caused.

**Comment by Miepee** [comment]
Don't get me wrong, it's still an issue, just at the wrong place.

**Comment by Detrixukaon58** [comment]
Oh, I found that I was looking at the wrong option, so it was just a non-issue. Again sorry about that.
