### ISSUE TITLE
Use proper directories for fetched files on unix

### ISSUE THREAD

**Issue by IvarWithoutBones** [AM2R-Community-Developers/AM2RLauncher#14]
Currently, the launcher attempts to write some patches, and a github repository to the directory the executable is placed in.

This results in the application being impossible to package, as you do not want to pollute (for example) `/usr/bin`. This is especially required for NixOS support, for which I've written an derivation. It currently crashes as it tries to write to the nix store, which is not meant to be modified by applications other than the package manager.

I suggest `$HOME/.local` being used for these, or alternatively `/tmp`.

**Comment by Miepee** [comment]
Pushed Commit `db77e29`, tell me if this works for you and if you have any issues.

**Comment by Miepee** [comment]
Has been fixed
