### ISSUE TITLE
Dependency for Linux not listed: libappimage

### ISSUE THREAD

**Issue by Koppajin** [AM2R-Community-Developers/AM2RLauncher#15]
Launcher would constantly crash... noticed program trying to create an .AppImage file when launched from a terminal so I had to install libappimage, this worked for me. Arch Linux btw.

**Comment by Miepee** [comment]
Are you sure that it's `libappimage` that's required?
Pretty sure that it's `fuse2` to be more exact.

I have an [Git-PKGBUILD](https://aur.archlinux.org/packages/am2rlauncher-git/) on the AUR, that one should have all required dependencies.

**Comment by Miepee** [comment]
Fixed with `8d1a493`
