### ISSUE TITLE
Switch Pro Controller not detected

### ISSUE THREAD

**Issue by ISSOtm** [AM2R-Community-Developers/AM2RLauncher#17]
OS: Arch Linux x64
Launcher version: 711a1b77a352340e4274e0560ed55e26657d3794
Pro Controller driver: [hid-nintendo-dkms](https://aur.archlinux.org/packages/hid-nintendo-dkms) 3.1-2

It just appears not to be detected :/
It *is* detected by the 1.1 game under Wine, though.

**Comment by Miepee** [comment]
Known, it's not an issue with the AM2RLauncher, it's an issue with AM2R itself.
Basically, the game only sees the IMU/Gyro as the controller.
Related to this issue https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/issues/76

**Comment by Miepee** [comment]
Out of curiosity, have you tried using Steam, enabling the Steam Switch Controller Support and launching the game like that?
I needed to do this for another project I was recently testing, that solved it for me.
