### ISSUE TITLE
No Audio In Game With Arch Linux And PipeWire

### ISSUE THREAD

**Issue by Duder963** [AM2R-Community-Developers/AM2RLauncher#24]
As the title states, on Arch Linux, there's no audio in game. Executing AM2R.AppImage from the terminal shows a stream of OpenAL errors. I am using pipewire, so that could be the issue.

These errors continuously repeat in the terminal.
```
OpenAL error: 40964 (SoundHardware::Tick)
OpenAL error: 40964 (Audio_Tick Start)
OpenAL error: 40964 (Audio_Tick End)
```

**Comment by Miepee** [comment]
You may be missing these packages:
`lib32-libopenal` and `lib32-libpulse`

**Comment by Duder963** [comment]
Yep. `lib32-libpulse` solved it
