### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by jeryd** [AM2R-Community-Developers/AM2RLauncher#25]
Using Wine under Fedora. Getting a failure to start (after downloading patches and applying 1.1 zip). What is needed to figure this out?

**Comment by Lojemiru** [comment]
Dependencies are listed on each release page. Once the launcher is set up, you'll likely need to add a launch flag to the game to prevent it from crashing as per the readme at https://github.com/AM2R-Community-Developers/AM2R-Autopatcher-Linux

**Comment by Miepee** [comment]
Closed by new 2.2.0 AM2RLauncher release / merging of gpu-fix on Autopatcher-Linux.
Delete and reinstall the profile (go to the mod settings tab, open the `open profile content folder` button, delete the folder it opens`).
Should you still have issues, feel free to reopen it.
