### ISSUE TITLE
[Include dependency] - Ubuntu 20.04

### ISSUE THREAD

**Issue by ZacharyFoxx** [AM2R-Community-Developers/AM2RLauncher#28]
Hi.

Just to improve the [faq](https://am2r-community-developers.github.io/DistributionCenter/faq.html#how-is-am2r-still-being-updated-didnt-the-developers-get-a-dmca), please:

- Include libstdc++ 6: i386 dependency for ubuntu and variants.

Without it the game doesn't start.

- The .NET Runtime must be version 5.0. AM2RLauncher refuses to start with version 6.0

**Comment by Miepee** [comment]
Hi, for the first one, I made a PR for it here (<https://github.com/AM2R-Community-Developers/DistributionCenter/pull/9>) that adds the dependencies AM2R itself needs. Should be merged soonish.

For the second one, I just addressed that in f417c6901faa556a75505b67f1cb99685823d6cd

**Comment by Miepee** [comment]
Pull request was merged, closing the issue.
