### ISSUE TITLE
AM2R silently crashes on Pop!_OS 20.10 (Ubuntu)

### ISSUE THREAD

**Issue by cobalt2727** [AM2R-Community-Developers/AM2RLauncher#3]
Logs are attached:

-----------------------------------------------------------------------------------

> cobalt@cobalt-inspiron:~$ ./am2r.sh 

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.331: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44e20 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.332: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44cb0 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.332: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44860 adjusted size vertical min 15 natural 15 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.362: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996b60b40 adjusted size vertical min 14 natural 14 must not decrease below min 16 natural 16

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.586: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44e20 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.587: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44cb0 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:26.587: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44860 adjusted size vertical min 15 natural 15 must not decrease below min 17 natural 17
> this is the part where i click PLAY

***************************************
*     YoYo Games Linux Runner V1.3    *
***************************************	 
CommandLine: -game game.unx
ExeName= /tmp/.mount_AM2R.AhJ3E3i/usr/bin/AM2R
MemoryManager allocated: 17920

***************************************
*     YoYo Games Runner v1.0(999)[r32908]    *
***************************************	 
RunnerLoadGame: game.unx
RunnerLoadGame() - assets/game.unx
Checking if INIFile assets/options.ini Exists
!!!!No INI File assets/options.ini
Reading File assets/game.unx
Loaded File assets/game.unx(68872432)
IFF wad found
Get Resolution
Get Header Information
InitGMLFunctions
HighScore..SavePrePend /home/cobalt/.config/AM2R/ 
Game..Math..Graphic..Action..File..Resource..Interaction..3D..Particle..Misc..DS..Sound..Physics..Gamepad..GAMEPAD: Initialising Ubuntu support
GAMEPAD: 4 axis values (last) at 0xf6819660
GAMEPAD: 4 axis values (last) at 0xf6819640
GAMEPAD: 4 axis values (last) at 0xf6819620
GAMEPAD: 4 axis values (last) at 0xf6819600
Buffers..Networking..Shaders..InitPushFunctions...YoYo..Fini
ID_STRG
Create Window
Display Size(Pixels): 1920,1080
GameDisplayName=AM2R
Win #1
XF86VidModeExtension-Version 2.2
Got Doublebuffered Visual!
glX-Version 1.4
Icon: w=72 h=72
sw=1920 wh=1080
WindowCentre: 800,420
Depth 24
Congrats, you have Direct Rendering!
sync = 0
**** GLX Extensions ***
GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync 
Checking for GLX_EXT_swap_control
Checking for GLX_SGI_swap_control
Vsync: GLX_SGI
DOUBLE BUFFERED
Init Graphics
GR_D3D_Init()
OpenGL: version string 3.0 Mesa 21.0.0
OpenGL: vendor string Intel Open Source Technology Center
OpenGL GLSL: version string 1.30
Check TextureID
finished(2)!!
Texture #1 16,16
Texture #2 16,16

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:37.180: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44e20 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:37.180: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44cb0 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:37.180: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44860 adjusted size vertical min 15 natural 15 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:37.229: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44e20 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:37.230: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44cb0 adjusted size vertical min 16 natural 16 must not decrease below min 17 natural 17

(AM2RLauncher:235440): Gtk-WARNING **: 16:31:37.230: __gtksharp_1_Eto_GtkSharp_Forms_EtoEventBox 0x55e996a44860 adjusted size vertical min 15 natural 15 must not decrease below min 17 natural 17
cobalt@cobalt-inspiron:~$

**Comment by Miepee** [comment]
Hello!
Since it's AM2R crashing, I *think* this is the wrong repository, but this needs to be confirmed first.

1. Why are you executing `am2r.sh` instead of the Launcher? Is it just a shell shortcut to the Launcher?
2. Can you post a neofetch for specs please? Would help with troubleshooting the issue, as AM2R is weird.
3. Can you launch the AppImage normally? It's located in `AM2RLauncherFolder/Profiles/Community Updates (Latest)/AM2R.AppImage`
4. Next time, could you put all the log files into coding blocks 😅 ? Makes it a ton easier to read.

**Comment by cobalt2727** [comment]
1. Yeah, I basically just use it to run AM2RLauncher.Gtk - I can confirm the same thing happens if I run that directly


2. 
OS: Pop!_OS 20.10 x86_64 
Host: Inspiron 15-7579 
Kernel: 5.11.0-7612-generic 
Uptime: 1 hour, 3 mins 
Packages: 3537 (dpkg), 33 (flatpak) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 3.38.3 
CPU: Intel i5-7200U (4) @ 3.100GHz 
GPU: Intel HD Graphics 620 
Memory: 2712MiB / 7729MiB 


3. It also immediately crashes...
`cobalt@cobalt-inspiron:~$ ./AM2R/Profiles/Community\ Updates\ \(Latest\)/AM2R.AppImage `

***************************************
*     YoYo Games Linux Runner V1.3    *
***************************************	 
CommandLine: -game game.unx
ExeName= /tmp/.mount_AM2R.AHv9gBl/usr/bin/AM2R
MemoryManager allocated: 17920

***************************************
*     YoYo Games Runner v1.0(999)[r32908]    *
***************************************	 
`RunnerLoadGame: game.unx`
`RunnerLoadGame() - assets/game.unx`
`Checking if INIFile assets/options.ini Exists`
`!!!!No INI File assets/options.ini`
`Reading File assets/game.unx`
`Loaded File assets/game.unx(68872432)`
`IFF wad found`
`Get Resolution`
`Get Header Information`
`InitGMLFunctions`
`HighScore..SavePrePend /home/cobalt/.config/AM2R/`
`Game..Math..Graphic..Action..File..Resource..Interaction..3D..Particle..Misc..DS..Sound..Physics..Gamepad..GAMEPAD: `
`Initialising Ubuntu support`
`GAMEPAD: 4 axis values (last) at 0xf6875660`
`GAMEPAD: Enumerating 5`
`GAMEPAD: device name Microsoft X-Box 360 pad`
`GAMEPAD: buttons - 11, axes - 8`
`GAMEPAD: 4 axis values (last) at 0xf6875620`
`GAMEPAD: 4 axis values (last) at 0xf6875600`
`GAMEPAD: 4 axis values (last) at 0xf68755e0`
`Buffers..Networking..Shaders..InitPushFunctions...YoYo..Fini`
`ID_STRG`
`Create Window`
`Display Size(Pixels): 1920,1080`
`GameDisplayName=AM2R`
`Win #1`
`XF86VidModeExtension-Version 2.2`
`Got Doublebuffered Visual!`
`glX-Version 1.4`
`Icon: w=72 h=72`
`sw=1920 wh=1080`
`WindowCentre: 800,420`
`Depth 24`
`Congrats, you have Direct Rendering!`
`sync = 0`
`**** GLX Extensions ***`
`GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float` `GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age` `GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float` `GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info` `GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent` `GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control` `GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group` `GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync `
`Checking for GLX_EXT_swap_control`
`Checking for GLX_SGI_swap_control`
`Vsync: GLX_SGI`
`DOUBLE BUFFERED`
`Init Graphics`
`GR_D3D_Init()`
`OpenGL: version string 3.0 Mesa 21.0.0`
`OpenGL: vendor string Intel Open Source Technology Center`
`OpenGL GLSL: version string 1.30`
`Check TextureID`
`finished(2)!!`
`Texture #1 16,16`
`Texture #2 16,16`
`Segmentation fault (core dumped)`
`cobalt@cobalt-inspiron:~$ `

**Comment by Miepee** [comment]
Ah yes, this is a known issue with intel HD graphics on Ubuntu (/Debian?) derivatives.
To fix this, start the Launcher, go to "Settings" and input `LIBGL_DRI3_DISABLE=1` into the Custom Environment Variable textbox.
This is not a Launcher issue, it's an issue with the AppImage, generated through the [Linux-Autopatcher](https://github.com/AM2R-Community-Developers/AM2R-Autopatcher-Linux/).

Although we could make a check for the first boot up of the launcher, check if current Distro is debian / ubuntu related and has intel hd graphics, and if yes, we just input the custom env var for them.

**Comment by cobalt2727** [comment]
That worked perfectly, thanks!
