### ISSUE TITLE
Controller Support not working on Manjaro Linux

### ISSUE THREAD

**Issue by Schweini07** [AM2R-Community-Developers/AM2RLauncher#31]
**Describe the bug**
Using any Controller, the game does not recognize it. I've tried my PS4 controller and Gamecube controller, both of them not working. Interestingly it works when launching AM2R (as a standalone) trough WINE.

**Expected behavior**
AM2R should recognize the controller.

**Platform**
 - OS: Manjaro Linux 21.2.3 Qonos
 - AM2RLauncher Version: 2.2.0

**Additional context**
 It could be related to https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/issues/76, but I would think that a PS4 controller should work? I event tried running the launcher through Steam, that didn't work either.

**Log file**
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/8015345/AM2RLauncher.log)

**Comment by Miepee** [comment]
Try going to controller settings and enabling compatibility mode.

**Comment by Schweini07** [comment]
That did the trick, thank you very much! Should've looked a little more at the settings.
