### ISSUE TITLE
AM2R does not launch or install via Flatpak

### ISSUE THREAD

**Issue by SingleSlice** [AM2R-Community-Developers/AM2RLauncher#33]
**Describe the bug**
AM2R does not launch on arch linux using the flatpak, the launcher itself works fine.

**Expected behavior**
well, it should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/32547537/183701331-a4651dc6-2ca9-42d4-bfed-89ed8eda4acd.png)

**Platform**
- arch linux, kde plasma wayland, on nvidia.

[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/9292760/AM2RLauncher.log)

**Comment by Miepee** [comment]
Few things:
A) Can you upload a log for the game itself? (~/.config/AM2R/logs)
B) Can you launch the AppImage normally, without it erroring? (In the launcher, go to Mod settings, and click on "open data directory" or similar)

**Comment by SingleSlice** [comment]
[Community Updates (Latest).txt](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/9292804/Community.Updates.Latest.txt)

here is the log, pretty empty.
and i cannot lunch the appimage normally

**Comment by Miepee** [comment]
Pretty empty indeed.
What happens if you launch the AppImage in a terminal, do you see any errors?

**Comment by SingleSlice** [comment]
![image](https://user-images.githubusercontent.com/32547537/183703571-b05b2afe-6385-4cb4-8b3d-13fdc08c6cd9.png)

sorry its in italian, but well, it says that on line 27: /tmp/.mount_AM2R.AqI85Wd/AppRun-game: file or directory does not exist

**Comment by Miepee** [comment]
(Hint for future: you can use the `LANG=C` environment variable to enforce english locale)
Can you check if you have fuse installed? `sudo pacman -Qs fuse`

**Comment by SingleSlice** [comment]
i do have fuse installed , yep

**Comment by Miepee** [comment]
Fuse2 or fuse3?
Also, check please if you have multilib enabled.

**Comment by SingleSlice** [comment]
i do have multilib enabled, and i do have both fuse2 and 3

**Comment by Miepee** [comment]
Hmm, that's strange. Usually the file not found error only appears either if fuse does not exist, or if multilib / the 32-bit packages aren't locally installed.

**Comment by SingleSlice** [comment]
ok so, i reinstalled the 32bit packages out of curiosity, and the appimage launches, though, the flatpak version does not work anyways.

**Comment by Miepee** [comment]
Well, that's slight improvement at least.
Does KDE show any error when trying to click "play" in the flatpak launcher?
Also, this may sound really dumb, but have you tried restarting your machine yet?

**Comment by SingleSlice** [comment]
does not show any error, it just closes the launcher, and opens it again.
and no i did not try that, ill try now though

**Comment by SingleSlice** [comment]
i did try rebooting my pc, still wont work

**Comment by Miepee** [comment]
Unfortunately, launching AppImages within Flatpaks is a bit of a hack.
I have an idea to solve it, but it'd need to wait until 2.3.0.

**Comment by Miepee** [comment]
@SingleSlice in case you're interested in testing, there's a current WIP in master to fix that issue.
You can install a flatpak test build with the instructions on this pull request at the very bottom.
https://github.com/flathub/io.github.am2r_community_developers.AM2RLauncher/pull/1

**Comment by dylan10182000** [comment]
Yeah I'm having the same issue. Also on Arch using KDE Plasma. The linked PR isn't installing either. Just gives a 404 error.

**Comment by Miepee** [comment]
I need testing on that PR since that'll likely be the solution we'll use going forwards.
What exactly gives a 404 error, following the instructions from here?
https://github.com/flathub/io.github.am2r_community_developers.AM2RLauncher/pull/1#issuecomment-1247090260

**Comment by Miepee** [comment]
New build commissioned, available here for now
https://github.com/flathub/io.github.am2r_community_developers.AM2RLauncher/pull/1#issuecomment-1260485080

I forgot that these are only available for 5 days, before they get revoked. If someone wants to test those builds again and they're not available / 404, just ping me here.
