### ISSUE TITLE
Linux: Error when clicking "Download" button

### ISSUE THREAD

**Issue by Leshuguita** [AM2R-Community-Developers/AM2RLauncher#40]
**Describe the bug**
Just installed it, following the instructions from https://github.com/AM2R-Community-Developers/AM2RLauncher/wiki/Installation-Process#arch-linux, and an error pops up when clicking the Download button, saying "The type initializer for 'Libgit2Sharp.Core.NativeMethods' threw an exception"

**Platform**
 - OS: Arch Linux
 - AM2RLauncher Version: 2.3.0

**Additional context**

**Log file**
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/10377676/AM2RLauncher.log)

**Comment by Miepee** [comment]
When was the last time you `-Syu`d? If it wasn't some time recently, can you try to `-Syu`, reboot, and see if it still happens?
Also, from where did you get the launcher? The release on github, some aur package (if yes, which) or from flathub?

**Comment by Leshuguita** [comment]
I'd last `-Syu`d yesterday, before installing everyting. Still happens after another `-Syu` and a reboot, with both the `am2rlauncher` and `am2rlauncher-git` packages

**Comment by Miepee** [comment]
Hm, need to check later whether I can replicate.
In the meantime, would you be able to test the following:
Clone the Repo, and modify the following line in [`AM2RLauncher.csproj`](https://github.com/AM2R-Community-Developers/AM2RLauncher/blob/main/AM2RLauncher/AM2RLauncher/AM2RLauncher.csproj)
```diff
-     <PackageReference Include="LibGit2Sharp" Version="0.26.2" />
+     <PackageReference Include="LibGit2Sharp" Version="0.27.0-preview-0182 " />
```
Then try to compile it (instructions should be both in the Wiki, as well as in the [PKGBUILD of `am2rlauncher-git`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=am2rlauncher-git)

**Comment by Leshuguita** [comment]
Still not working, but different error: "could not load ssl libraries"
Logs: 
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/10387020/AM2RLauncher.log)

**Comment by Miepee** [comment]
That sounds like https://github.com/libgit2/libgit2sharp/issues/2003
According to the thread there, using `0.27.0-preview-0182` should fix it. What if for compiling, instead of using `-r ubuntu.18.04-x64`, you use `-r ubuntu.20.04-x64`?

**Comment by Leshuguita** [comment]
Didn't work either, same error.
It managed to start the download after installing the `openssl-1.1` package, though I do not know if that's option on other distros

**Comment by Miepee** [comment]
It probably is, but I wouldn't rely on it.
I guess something that can be tried as well is to just check all the 0.27 preview packages here and see if any one of them works? (and obviously remove openssl-1.1 before attempting)
https://www.nuget.org/packages/LibGit2Sharp/#versions-body-tab

**Comment by rehtlaw** [comment]
any updates on this? the error still persists

**Comment by Miepee** [comment]
As this is an upstream issue, the error will persist until it's fixed upstream. Updates will more likely be found in the linked libgit2sharp issue from above than here.

**Comment by Miepee** [comment]
@rehtlaw @Leshuguita I've updated to the newest libgit2sharp release, can you pull down the artifacts and see if the error persists?
(https://github.com/AM2R-Community-Developers/AM2RLauncher/actions/runs/4667573051)

**Comment by Leshuguita** [comment]
Nope, it works now!

**Comment by Miepee** [comment]
> Nope, it works now!

Do you have `openssl-1.1` installed? If yes, can you please remove it and try without it again?

**Comment by rehtlaw** [comment]
I made sure to delete openssl-1.1 before, and it also works for me.

**Comment by Miepee** [comment]
Thank you! If anyone still has that error, feel free to reopen this issue.

**Comment by Miepee** [comment]
Not unless I can see any log info.

**Comment by Magicrafter13** [comment]
still not merged into a release?

**Comment by Miepee** [comment]
We have not made a new release since then, no.
