### ISSUE TITLE
Am2r launcher 2.0 doesnt install the new version of Am2r

### ISSUE THREAD

**Issue by Felipefpl** [AM2R-Community-Developers/AM2RLauncher#5]
I got the zip version of 1.5 release and then tried to add manually in the launcher but i got a msg saying that isnt the 1.1 version, only the 1.1 version could be installed.

**Comment by lassiterm** [comment]
That's intended. All Community Updates are patched on top of 1.1, not any other version. Providing a 1.1 zip to the launcher is required for it to work.

**Comment by Felipefpl** [comment]
> That's intended. All Community Updates are patched on top of 1.1, not any other version. Providing a 1.1 zip to the launcher is required for it to work.

I see, it woudl be nice if there was a msg saying to avoid inserting newer versions though. ;) - it would avoid waste of time.

But there is no info in the launcher if the 1.1 version was updated to 1.5.2 :/

**Comment by Miepee** [comment]
> I see, it woudl be nice if there was a msg saying to avoid inserting newer versions though. ;) - it would avoid waste of time.
There are messages saying that. There is a big fat button called "SELECT 1.1", along with multiple other text referring to it.

> But there is no info in the launcher if the 1.1 version was updated to 1.5.2 :/
After you selected the AM2R 1.1.zip, it will show a big fat "INSTALL" button, which installs the latest (or I think the Launcher calls it, the most up-to date" version. If you can see the "PLAY" button, that means you are on latest.

Closing this, as this is a non-issue.

**Comment by lassiterm** [comment]
![image](https://user-images.githubusercontent.com/8270851/115060491-88684e00-9ead-11eb-97c7-19c1a8ccff0e.png)

Like Miepee said, this shows the "PLAY" button with the version number at the bottom.

**Comment by Felipefpl** [comment]
> There are messages saying that. There is a big fat button called "SELECT 1.1", along with multiple other text referring to it.

Only select 1.1, it doesnt say you cant install newer versions.

> After you selected the AM2R 1.1.zip, it will show a big fat "INSTALL" button, which installs the latest (or I think the Launcher calls it, the most up-to date" version. If you can see the "PLAY" button, that means you are on latest.

I see, i didnt see the info about the version in-game as it's usual to see in the PC games.

**Comment by Miepee** [comment]
> Only select 1.1, it doesnt say you cant install newer versions.

Yes. If it only says you should select 1.1, then that means you *need* to select 1.1. If you could've selected anything else as well, it would've said so.

> I see, i didnt see the info about the version in-game as it's usual to see in the PC games.

Not only is the version shown on the launcher, it is *also* shown in-game at the title screen.
