### ISSUE TITLE
[Wiki] Typo in dependencies for Fedora

### ISSUE THREAD

**Issue by matteodev8** [AM2R-Community-Developers/AM2RLauncher#58]
At `pulseaudio-libs.1686` there is a `1` instead of an `i`

![image](https://github.com/AM2R-Community-Developers/AM2RLauncher/assets/59450459/c8e5b787-a8dd-404c-8fd8-e8011ca98eb5)

https://github.com/AM2R-Community-Developers/AM2RLauncher/wiki/Installation-Process#fedora

**Comment by Miepee** [comment]
Fixed, thanks
