### ISSUE TITLE
Feature Request: Allow the use of the directional pad when using playstation controllers.

### ISSUE THREAD

**Issue by TomTurbine** [AM2R-Community-Developers/AM2RLauncher#61]
Just discovered this but noticed that when using a dual sense controller I could only move while using the analog stick, the directional pad didn't do anything.

Just suggesting that be included in a future update.

As an aside, I just discovered this project today and speaking as someone who still owns the original game boy cartridge, thank you very much.

**Comment by Lojemiru** [comment]
Thank you for the report, but please do not open game issues on this repository. This is for the AM2RLauncher only, not for the game itself.

This issue with PlayStation controllers is known and will be addressed in update 2.0, which is undergoing work and issue tracking in a private repository.
