### ISSUE TITLE
Portuguese translation clips at a few points

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/AM2RLauncher#7]
Apparently the brazilian translation clips at some spots.
@Felipefpl Could you provide screenshots on where it was broken please? I didn't find anything obvious that clips here

**Comment by Felipefpl** [comment]
I tried to copy/save the image on paint using print screen but it didnt work for an unknown reason, you will find those problems mostly in the options.

**Comment by Miepee** [comment]
![grafik](https://user-images.githubusercontent.com/38186597/115763089-6f2b3a00-a3a4-11eb-8c54-179b86abb88a.png)
Seems fine to me

**Comment by Felipefpl** [comment]
Miepee - sorry but you changed the place of the problem, it should be here https://github.com/Felipefpl/AM2R-Localizations :package: - i'm talking about the options in-game ;)


Also, how did you add that translation (a bad one i must say) to am2r? I created a folder/added the file but i couldnt change the language

**Comment by Miepee** [comment]
> i'm talking about the options in-game ;)

Yeah, that's what I was confused upon.

> Also, how did you add that translation (a bad one i must say) to am2r?

This is not AM2R, this is the AM2RLauncher. Can you specify what's bad about it?

**Comment by Miepee** [comment]
> 
> 
> Miepee - sorry but you changed the place of the problem, it should be here https://github.com/Felipefpl/AM2R-Localizations 📦 - i'm talking about the options in-game ;)
> 
> Also, how did you add that translation (a bad one i must say) to am2r? I created a folder/added the file but i couldnt change the language

**Comment by Felipefpl** [comment]
> This is not AM2R, this is the AM2RLauncher.

I know. ;)

> Can you specify what's bad about it?

Several words werent translated as they should, several words that arent in the original text were included in the translated without any need, the original text is clear enough to be understood by everyone.

**Comment by Miepee** [comment]
Care giving examples?

**Comment by Miepee** [comment]
Closing this then in favour of the PR
