### ISSUE TITLE
[NixOS] Does not launch AM2R

### ISSUE THREAD

**Issue by Noodlez1232** [AM2R-Community-Developers/AM2RLauncher#73]
**Describe the bug**
On NixOS (using `nix run nixpkgs#am2rlauncher`), AM2R does not launch, but instead the launcher simply opens again.

**Expected behavior**
AM2R launches

**To Reproduce**
1. run AM2R launcher using `nix run nixpkgs#am2rlauncher`
2. Try to run AM2R from the Launcher
3. Failure

**Screenshots**

**Platform**
 - OS: NixOS using nixpkgs-unstable
 - AM2RLauncher Version: The nixpkgs custom packaged version (the rev in the nix build)

**Additional context**
The launcher failed to open up a file selection dialog (would crash), so I copied this configuration from the flatpak. I made sure to look around the files and stuff, however, and didn't find any references to paths that were speciifc to the flatpak version.

**Log file**
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/15003900/AM2RLauncher.log)

**Comment by Miepee** [comment]
Heya, we don't actually maintain the nixos package. IIRC that was done by @peeley , so you'd probably need to report it to them somewhere
