### ISSUE TITLE
[NixOS] Launcher does not let you select an AM2R.zip

### ISSUE THREAD

**Issue by Noodlez1232** [AM2R-Community-Developers/AM2RLauncher#74]
**Describe the bug**
Upon trying to select a .zip file, the launcher will hang, then crash with a segfault.

**Expected behavior**
A dialog box pops up

**To Reproduce**
1.  Launch into a new launcher
2.  Try to select a .zip file (the first button on the launcher)
3. Failure

**Screenshots**

**Platform**
 - OS: NixOS (nixpkgs-unstable)
 - AM2RLauncher Version: The custom rev used by the nixpkgs

**Additional context**
If needed I can provide my NixOS config as well

**Log file**
This may not be the correct one, but it is the oldest one I have.
[AM2RLauncher.7.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/15003910/AM2RLauncher.7.log)

**Comment by Miepee** [comment]
see #73
