### ISSUE TITLE
[Linux Mint] Flatpak version error encountered when clicking play button System.ComponentModel.Win32Exception(2)

### ISSUE THREAD

**Issue by jjhen99** [AM2R-Community-Developers/AM2RLauncher#81]
**Describe the bug**
I have installed the flatpak version of AM2R Launcher and have selected a copy of AM2R_1.1.zip. 
When I click the green play button, I encounter the following error:
![image](https://github.com/AM2R-Community-Developers/AM2RLauncher/assets/141966475/3a92c9c0-ba9b-4a50-9cff-a983a0941861)

**Expected behavior**

**To Reproduce**
1. Install AM2R Launcher from [flathub](https://flathub.org/apps/io.github.am2r_community_developers.AM2RLauncher)
2. Used `flatpak install runtime/org.gnome.Platform/x86_64/42` since I encountered a previous error because I had not installed this
3. Click 'download'
4. Selected AM2R_1.1.zip (the original zip file did not have this name, I renamed it to AM2R_1.1.zip)
5. Press the green play button

**Platform**
 - OS: Linux Mint 21.3
 - AM2RLauncher Version: 2.3.0

**Log file**
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/15420241/AM2RLauncher.log)

**Comment by Miepee** [comment]
You need to install the 32bit version of the runtime as well. I believe it's called `org.gnome.Platform.Compat.i386`
