### ISSUE TITLE
Unable to navigate the menu or move around in the game

### ISSUE THREAD

**Issue by Sebas-om** [AM2R-Community-Developers/AM2RLauncher#83]
**Describe the bug**
When starting the game, it just acts like it's pressing up and to the left

**Screenshots**

**Platform**
 - OS:Windows 10 pro
 - AM2RLauncher Version: 2.3.0

**Additional context**
-Simple video showing the problem:
[AM2R report video.zip](https://github.com/user-attachments/files/16445462/AM2R.report.video.zip)
Yep, I've tried several keyboards, I don't think it's my PC

**Log file**
[AM2RLauncher.logs,1,2,3.zip](https://github.com/user-attachments/files/16445374/AM2RLauncher.logs.1.2.3.zip)

**Comment by Miepee** [comment]
You have some device plugged in thats being recognized as a controller.
Either an actual controller, or maybe some tablet/fancy mouse/something else.

**Comment by Sebas-om** [comment]
Nope, the only thing I have connected is my mouse, keyboard and USB Bluetooth

**Comment by Sebas-om** [comment]
Forget it I didn't notice my Wii Remote (it was on under some things on my desk)
