### ISSUE TITLE
ERROR DOWNLOAD BUTTON LINUX

### ISSUE THREAD

**Issue by SerShef** [AM2R-Community-Developers/AM2RLauncher#87]
USING THE LINUX RELEASE .ZIP...
UPON SELECTING THE DOWNLOAD BUTTON IN THE LAUNCHER I AM MET WITH THIS ERROR...
![Screenshot from 2024-09-17 01-03-21](https://github.com/user-attachments/assets/a054a87c-c539-43bb-9abc-5d2fd6343455)

**Comment by Miepee** [comment]
Known, duplicate of #40
The workaround is to use the flatpak version in the meantime until a new release is made.

**Comment by SerShef** [comment]
> Known, duplicate of #40 The workaround is to use the flatpak version in the meantime until a new release is made.

THE FLATPAK VERSION I COULD NOT MAP SOME CONTROLS...
I RUN WINDOWS VERSION THROUGH PROTON FOR NOW...
