### ISSUE TITLE
.NET 6 has hit EOL

### ISSUE THREAD

**Issue by GGG-KILLER** [AM2R-Community-Developers/AM2RLauncher#93]
.NET 6 has hit EOL on November 12, 2024[^1] and will no longer be supported nor receive updates.
Recommended path is to upgrade either to .NET 8 (LTS) or .NET 9 (STS).

We've hit this while removing .NET 6 and 7 from nixpgks: https://github.com/NixOS/nixpkgs/issues/326335.

[^1]: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by Miepee** [comment]
Thanks for the heads up.
Unfortunately I'm not quite sure when i'll be able to get to this, hopefully around christmas period
